version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres-yaycha
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thuraminthein12345
      - POSTGRES_DB=yaycha_dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yaycha_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  yaycha-app:
    build: .
    container_name: yaycha-app
    ports:
      - "3333:3333"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped

volumes:
  postgres_data:
